#!/bin/sh

# Fail if these vars are not present (e.g. from direct wrapper runs)
: ${SNAP?} ${SNAP_DATA?}
# Copy only if not existing
cp -pn $SNAP/etc/bitlbee/bitlbee.conf $SNAP_DATA/bitlbee.conf
exec $SNAP/usr/sbin/telegraf -F -n --config $SNAP_DATA/bitlbee.conf
