name: bitlbee-sajoupa
version: 3.5.1
summary: An IRC to other chat networks gateway
description:
  BitlBee brings IM (instant messaging) to IRC clients.
  It's a great solution for people who have an IRC client
  running all the time and don't want to run an additional
  MSN/AIM/whatever client.
confinement: strict
base: core18
grade: stable

apps:
  bitlbee:
    command: 'bin/bitlbee.wrapper'
    daemon: simple
    plugs:
      - network-bind
      - home

parts:

  snap-wrappers:
    after: [telegram-purple]
    plugin: dump
    source: .
    organize:
      bitlbee_wrapper: bin/bitlbee.wrapper

  telegram-purple:
    plugin: autotools
    source: https://github.com/majn/telegram-purple.git
    stage-packages:
      - bitlbee-dev
      - bitlbee-libpurple
      - gettext
      - libglib2.0-dev
      - libgnutls28-dev
      - libgcrypt20-dev
      - libgpm2
      - libjson-glib-dev
      - libotr5-dev
      - libpng-dev
      - libprotobuf-c-dev
      - libpurple-dev
      - libwebp-dev
      - protobuf-c-compiler
