#!/bin/bash

# Create the directory where btitlbee stores accounts settings
[ -d $SNAP_USER_DATA/user_configs ] || mkdir $SNAP_USER_DATA/user_configs
chmod 700 $SNAP_USER_DATA/user_configs

if [ -f $SNAP_USER_DATA/biltbee.conf ] ; then
  echo "Using existing conf file $SNAP_USER_DATA/biltbee.conf."
  echo "Remove it to generate a new one from the template at next run."
  echo "Starting bitlbee..."
else
  echo "Creating config file $SNAP_USER_DATA/biltbee.conf..."
  sed "s,.*ConfigDir = .*,ConfigDir = $SNAP_USER_DATA/user_configs," $SNAP/etc/bitlbee.conf > $SNAP_USER_DATA/biltbee.conf
  echo "Starting bitlbee..."
fi

$SNAP/sbin/bitlbee -F -c $SNAP_USER_DATA/biltbee.conf
